# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - chickendiseaseprediction

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://chickendiseaseprediction.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_3dcd49657cd5455cb98b85a8cc842520 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_8cace167b69f49bfb2742a5700a56a75 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: chickendiseaseprediction.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3dcd49657cd5455cb98b85a8cc842520 }}/chickendiseaseprediction:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'chickendiseaseprediction'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b11505835c4c4c4287f2229fc84fe72a }}
        images: 'chickendiseaseprediction.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3dcd49657cd5455cb98b85a8cc842520 }}/chickendiseaseprediction:${{ github.sha }}'